name: keyword-releaser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: damo-maker/actions-custom@main
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: 'FIXED'
    - run: |
        gh api damo-maker/actions-custom/
    
