name: keyword-releaser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: damo-maker/actions_custom@main
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_CUSTOM_KEY }}
      with:
        args: 'FIXED'
